xmin = -94.4375+360;
xmax = -88.1875+360;
ymin = 28.9375;
ymax = 37.9375;
scale_factor = 12.5;

clm_gridded_domain_filename = 'domain.lnd.nldas2_0224x0464_c110415.nc';
clm_gridded_surfdata_filename = 'surfdata_nldas2_simyr2000_c181207.nc';

CreateCLMSgridSurfdatForE3SM(...
                    xmin, xmax, ymin, ymax,...
                    clm_gridded_surfdata_filename, ...
                    '.', 'LowerMiss', scale_factor)

CreateDomainSgridInputForE3SM(...
                    xmin, xmax, ymin, ymax,        ...
                    clm_gridded_domain_filename,   ...
                    '.',                ...
                    'LowerMiss', scale_factor)